grub: Do not read list files when secure-boot is enabled
The list of all fs modules we ship is generated at compile time and
saved in a file called `fs.lst`. At boot time GRUB reads this file and
creates a list of available modules that is used (among others) by the
`autofs` module.

Unfortunately when we boot in EFI + secure-boot mode, even though the
modules are actually present in the prefix location, we cannot access
them since we cannot load any external module. This results in the
annoying error message:

    error: Secure Boot forbids loading module from (memdisk)/boot/...

With this patch we avoid reading the list files (including `fs.lst`) at
boot-time when we are in EFI + secure-boot mode.

https://phabricator.endlessm.com/T13311

Signed-off-by: Carlo Caione <carlo@endlessm.com>