conf: use C:\endless\grub\grubenv
This is essentially a revert of
026955347bbccd570ba38a6eefcddc6feba28006. It turns out that GRUB's
loopback module does not implement writing back to the loop device, so
attempting to save the last-selected menu entry to /boot/grub/grubenv
inside the image does not work. My bad.

Until we either implement write support in GRUB's loopback module, or
teach the OS how to access C:\endless\grub\grubenv, we need to disable
the 'recordfail' mechanism on dual-boot systems.

Without this change, dual-boot users see the following when they select
a boot menu entry:

    error: loopback write is not supported.

    Press any key to continue...

(with an extra 'error:' in the EFI case where we attempt to write to
grubenv twice)

https://phabricator.endlessm.com/T18551