conf: avoid "file '/grubenv' not found" under eosldr
When loaded via eosldr, the following error is shown

    Error: file `/grubenv' not found.

    Press any key to continue...

(After pressing the Any Key, the system boot correctly, without a menu
from GRUB.) This is because $grubroot is only defined when eosldr is not
found.

We only want 'savedefault' to have any effect when we've shown a menu.
The correct conditions for that are ! $is_live && $eosimage && ! -f
($eosimage)/eosldr -- exactly the conditions under which $grubroot is
defined. So, make this explicit: define a variable for the path to the
'grubenv' file, and use this as the sole condition for savedefault to
have any effect.

https://phabricator.endlessm.com/T14545