blscfg: Workaround compiler bug
When compiling on OBS we get:

commands/blscfg.c:267:10: error: missing braces around initializer
[-Werror=missing-braces]
   struct parse_entry_ctx ctx = { 0 };

This is apparently a compiler bug:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=53119

Switch to the nonportable memset version.

Signed-off-by: Carlo Caione <carlo@endlessm.com>