build-sa-efi-images: ship 'read' module
This is used on the "Windows is hibernated" path. Without this, users
see the following:

    Press ENTER to continue ...
    error: file `/endless/grub/x86_64-efi/read.mod' not found.

    Press any key to continue...

https://phabricator.endlessm.com/T13600